/// glukoService
library gluko_service;

export 'src/Data/gluko_service.dart';
export 'src/Data/allfood_service.dart';
export 'src/Data/login_service.dart';
export 'src/Data/registerPlate_service.dart';
export 'src/Data/foodBarcode_service.dart';
export 'src/Model/plateRequest.dart';
export 'src/Data/signUp_service.dart';
export 'src/Data/emergency_service.dart';
export 'src/Data/report_service.dart';
export 'src/Data/infoUser_service.dart';
export 'src/Data/actualState_service.dart';
export 'src/Data/reportPDF_service.dart';
export 'src/Data/Recomendation_service.dart';
export 'src/Data/historialReports_service.dart';
export 'src/Data/emailValidate_service.dart';
export 'src/Data/allinsulin_service.dart';
export 'src/Data/typeuser_service.dart';
export 'src/Data/changePassword_service.dart';
export 'src/Data/resetPassword_service.dart';
export 'src/Data/editUser_service.dart';
